Repository EnigmaVSSUT/induction-2021-2nd-yr, pull requests merged in 2021-05, with the labels that each got.

#11 Task 1
  Backend Development using PHP/Task Submission/Adya Rath_Task 1/README.md
  Backend Development using PHP/Task Submission/Adya Rath_Task 1/api.php
  Backend Development using PHP/Task Submission/Adya Rath_Task 1/database.php
  Backend Development using PHP/Task Submission/Adya Rath_Task 1/index.php
Labels: Completed, PHP

#10 The task 1 for backend development using node is completed.
  Backend Development using Node/Task Submission/Barsha Baishaki Nayak/.gitignore
  Backend Development using Node/Task Submission/Barsha Baishaki Nayak/Procfile
  Backend Development using Node/Task Submission/Barsha Baishaki Nayak/app.js
  Backend Development using Node/Task Submission/Barsha Baishaki Nayak/index.html
  Backend Development using Node/Task Submission/Barsha Baishaki Nayak/package-lock.json
  Backend Development using Node/Task Submission/Barsha Baishaki Nayak/package.json
  Backend Development using Node/Task Submission/Barsha Baishaki Nayak/views/list.ejs
  Backend Development using Node/Task Submission/README.md
Labels: Completed, Node, Task 1

#20 Task 2
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/.htaccess
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/README.md
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/api/add.php
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/api/delete.php
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/api/quote.php
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/api/quotes.json
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/api/read.php
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/api/update.php
  Backend Development using PHP/Task Submission/AdyaRath_Task_2/index.php
Labels: Completed, PHP, Task 2

#13 Machine Learning task
  Machine Learning/Task Submission/Sohum.ipynb
Labels: Completed, ML

#15 Pr for machine learning task
  Machine Learning/Task Submission/krishna.ipynb
Labels: Completed, ML

#14 Submitting Machine Learning Task
  Machine Learning/Task Submission/Lopamudra_Nayak (1).ipynb
Labels: Completed, ML

#19 ML Task.
  Debashis_Behera (1).ipynb
  Machine Learning/Task Submission/Debashis_Behera (1).ipynb
Labels: Completed, ML
